export const SET_NAVBAR_ITEM = "[NAVBAR] SELECT ITEM";
export const SET_PREVIOUS_SECTION_HEIGHT = "[HEIGHT] SET PREVIOUS SECTION";

export const GET_BLOG_LIST_REQUEST = "[BLOG] GET LIST REQUEST";
export const GET_BLOG_LIST_SUCCESS = "[BLOG] GET LIST SUCCESS";
export const GET_BLOG_LIST_FAILURE = "[BLOG] GET LIST FAILURE";